eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8082
  servlet:
    contextPath: /pricing

spring:
  application:
    name: pricing

logging.file: pricing-service.log

---

spring:
  profiles: docker

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://registry:8761/eureka}
  instance:
    preferIpAddress: true

