server:
  port: 8761
 
spring:
  application:
    name: registry
     
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    service-url:
      defaultZone: http://localhost:8761/eureka

eureka.server.renewalPercentThreshold: 0.33
logging.file: registry-service.log

---

spring:
  profiles: docker

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://registry:8761/eureka/
    service-url:
      defaultZone: http://registry:8761/eureka
